version: '3'

services:
  app:
    image: au-hnpwa
    build: .
    volumes:
      - .:/src/app/
      - node_modules:/src/app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 5000:8080

volumes:
  node_modules:
